version: '3.8'
networks:
  app:

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "composer install &&
      php artisan serve --host=0.0.0.0"

    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    networks:
      - app