version: '3.8'
networks:
  app:

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "composer install &&
      php artisan serve --host=0.0.0.0"

    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app/
    networks:
      - app